# Hello World for AWS Lambda
service: node-boilerplate # Service Name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    service_name: ${self:service}

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          method: get
          path: /

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
